guests = ["Anurag","Pareek","Krsna"]
print("Hello, "+guests[0]+" .You are invited for the dinner")
print("Hello, "+guests[1]+" .You are invited for the dinner")
print("Hello, "+guests[2]+" .You are invited for the dinner")
print(guests[1]+" cannot come to the dinner.")
print("Inplace we are inviting \"Mr. Rohan\" for the dinner.")
guests[1] = "Rohan"
print(guests[1]+" .You are invited for the dinner, tonight.")
print(guests[0]+" .You are invited for the dinner, tonight.")
print(guests[2]+" .You are invited for the dinner, tonight.")
print("Now we are having a big dinning table. We would like to invite the following three more guests :\n1.Mr Rohit\n2.Mr Sohan\n3.Mr Sujit")
guests.insert(0,"Mr Rohit")
guests.insert(2,"Mr Sohan")
guests.append("Mr sujit")
print(guests[0]+", you are invited for the dinner tonight.")
print(guests[1]+", you are invited for the dinner tonight.")
print(guests[2]+", you are invited for the dinner tonight.")
print(guests[3]+", you are invited for the dinner tonight.")
print(guests[4]+", you are invited for the dinner tonight.")
print(guests[5]+", you are invited for the dinner tonight.")
print("It's seem that the big dinner table won't arrive in time.Sorry now we can only invite two persons.")
pop_1 = guests.pop()
print("Sorry "+pop_1+".We'll invite you next time.")
pop_2 = guests.pop()
print("Sorry "+pop_2+".We'll invite you next time.")
pop_3 = guests.pop()
print("Sorry "+pop_3+".We'll invite you next time.")
pop_4 = guests.pop()
print("Sorry "+pop_4+".We'll invite you next time.")
print(guests[0]+","+guests[1]+".You are welcome. You'r still invited for the dinner tonight.")
print("Total remaining guests are : ",len(guests))
del guests[0]
del guests[0]
print(guests)

